language: node_js
node_js:
  - "11"
services:
  - docker

  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - yarn test
  - docker build -t potterua/test .
  - docker push potterua/test
